### ISSUE TITLE
[Blocklist unavailable] blocklist.de

### ISSUE THREAD

**Issue by roofburner** [Ultimate-Hosts-Blacklist/www.blocklist.de#1]
Dear,

It seems "hxxps[://]lists[dot]blocklist[dot]de/lists/all[dot]txt" is down at the moment.

Kind regards

**Comment by smed79** [comment]
No problem here ...

![https://lists.blocklist.de/lists/all.txt](https://i.imgur.com/clV0lit.png)
![https://lists.blocklist.de/lists/all.txt](https://i.imgur.com/kOxVrEp.png)
